### PR TITLE
Admin can add a user to a team as a competitor

### PR DESCRIPTION
**Pull request by jonstorer**

### CODE REVIEW

**Comment by jjgonecrypto** [comment]
so just a heads up that competitors aren't always on a team - they can also be investors. actually need to add `can_invest` to Competitor.

**Comment by jjgonecrypto** [comment]
otherwise LFTM

**Comment by jonstorer** [comment]
@justinjmoses I disagree with that approach, I'll probably end up with an Investor model. I'll tie that in somehow, but competitors and investors are different things.

Also, can't all people invest? or did we change that?

**Comment by jjgonecrypto** [comment]
ok- that does sound like a better approach. 

no - only investors can compete.

**Pull request closed without merging**
